<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fss</groupId>
        <artifactId>flash-sale-system</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>fss-domain</artifactId>
    <name>fss-domain</name>
    <description>实体、Mapper、DTO、消息体。只依赖 common，不依赖 infra。</description>

    <dependencies>
        <dependency>
            <groupId>com.fss</groupId>
            <artifactId>fss-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
    </dependencies>
</project>
