# RocketMQ broker-b：第二个同步 Master，Topic 由 init-topics.sh 同步创建。
brokerClusterName = DefaultCluster
brokerName = broker-b
brokerId = 0
brokerIP1 = rocketmq-broker-b
listenPort = 11011
namesrvAddr = rocketmq-namesrv:9876;rocketmq-namesrv-b:9876
brokerRole = SYNC_MASTER
flushDiskType = ASYNC_FLUSH
aclEnable = true
timerWheelEnable = true
autoCreateTopicEnable = false
autoCreateSubscriptionGroup = true
diskMaxUsedSpaceRatio = 95
fileReservedTime = 6
