brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 1
brokerIP1 = rocketmq-broker-a-slave
listenPort = 10931
namesrvAddr = rocketmq-namesrv:9876;rocketmq-namesrv-b:9876
brokerRole = SLAVE
flushDiskType = ASYNC_FLUSH
aclEnable = true
timerWheelEnable = true
autoCreateTopicEnable = false
autoCreateSubscriptionGroup = true
diskMaxUsedSpaceRatio = 95
fileReservedTime = 6
